server:
  port: 9004

spring:
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 1000
      max-idle: 100
      max-wait: 5000
    timeout: 3000
    database: 0
  datasource:
    url: jdbc:mysql://10.176.73.161:3306/hxjian?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  output:
    ansi:
      enabled: always
  boot:
    admin:
      url: http://localhost:9000/otc-monitor/index
management:
  security:
    enabled: false
